### PR TITLE
Union

### PR DESCRIPTION
**Pull request by happy-san**
## Change Summary

* Sample request:
```bash
curl 'http://localhost:8108/multi_search?page=1&per_page=2' -X POST -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -d '
{
  "union": true,
  "searches": [
    {
      "collection": "posts",
      "q": "*",
      "filter_by": "user_name:stark_indus"
    },
    {
      "collection": "posts",
      "q": "*",
      "filter_by": "user_name:rogers_steve"
    }
  ]
}' | jq
```

* Sample response:

```json
{
  "found": 3,
  "hits": [
    {
      "document": {
        "content": "USA",
        "id": "124",
        "likes": 5215,
        "user_name": "stark_indus"
      },
      "highlight": {},
      "highlights": []
    },
    {
      "document": {
        "content": "CA",
        "id": "125",
        "likes": 2133,
        "user_name": "rogers_steve"
      },
      "highlight": {},
      "highlights": []
    }
  ],
  "out_of": 3,
  "page": 1,
  "search_cutoff": false,
  "search_time_ms": 0,
  "union_request_params": [
    {
      "collection": "posts",
      "first_q": "*",
      "per_page": 2,
      "q": "*"
    },
    {
      "collection": "posts",
      "first_q": "*",
      "per_page": 2,
      "q": "*"
    }
  ]
}
```

* Only global pagination parameters `"page"`, `"per_page"`, `"offset"`, `"limit"`, and the parameter `"limit_hits"` are taken into consideration in union. They are ignored when passed with individual searches. 

* `"sort_by"` with union requires all the searches to have the same type and number of fields and sorting order to work. For example:
```bash
{
  "union": true,
  "searches": [
    {
      ...
      "sort_by": "user_name:asc"
      ...
    },
    {
      ...
      "sort_by": "rating:asc"
      ...
    }
  ]
}
```
will return an error.
## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Review by kishorenc — APPROVED** [review]

**Comment by youradds** [comment]
Is it possible to "merge" the results so we don't end up with duplicated ids? (whilst still preserving the number of results asked for) 

Here is an example from when I do multiple searches using the `union` option, and `multi_search`:

```
Cartoon Bookworm Reading - 139324
Cartoon Bookworm Reading - 139324
vector kid working the computer cartoon - 393724
vector kid working the computer cartoon - 393724
Man holding a big birthday cake - 369271
Man holding a big birthday cake - 369271
kid carrying a stack books - 390647
kid carrying a stack books - 390647
Ipad touch screen - 380274
Ipad touch screen - 380274
Royalty Free RF Clipart Illustration Happy Geek Boy Waving Flat Design - 395758
Royalty Free RF Clipart Illustration Happy Geek Boy Waving Flat Design - 395758
Royalty Free RF Clipart Illustration Smiling Geek Boy Head - 395896
Royalty Free RF Clipart Illustration Smiling Geek Boy Head - 395896
cartoon-children 002 - 381567
cartoon-children 002 - 381567
child a computer - 389841
Cartoon Pencil Character Reading ABC Book - 388921
child a computer - 389841
Cartoon Pencil Character Reading ABC Book - 388921
image college student universitario - 393944
image college student universitario - 393944
kid reading paper - 393978
kid reading paper - 393978
small boy playing a computer cartoon - 397608
small boy playing a computer cartoon - 397608
female college student - 393905
female college student - 393905
vector black white kid working the computer cartoon - 393688
AI Human Integration Concept - 153496
vector black white kid working the computer cartoon - 393688
AI Human Integration Concept - 153496
male college student - 394785
male college student - 394785
cartoon nerd girl head vector clipart - 413043
cartoon nerd girl head vector clipart - 413043
```

I could obviously filter out the duplicates before rendering them, but that would throw the number of results off by however many duplicates I have. 

Thanks!

**Comment by happy-san** [comment]
Hi @youradds That is not possible right now. Can you create a feature request regarding this?

**Comment by youradds** [comment]
> Hi @youradds That is not possible right now. Can you create a feature request regarding this?

Thanks - I've just opened an issue: https://github.com/typesense/typesense/issues/2173

**Comment by marrishiva3** [comment]
How do I get facets results in union search ?

**Pull request merged**
