### PR TITLE
Dictionary based stemming

### PR DESCRIPTION
**Pull request by krunal1313**
## Change Summary

- add functionality to import plurals via end-point
- normalize plurals with stem_dictionary=true per field
- add test

## adding dictionary via end-point
To add plurals, we need to import jsonl file to end-point `/stemming/dictionaries/import` via POST request like below,
```curl
curl -k -H 'Content-Type:' -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -X POST --data-binary @plurals.jsonl "http://localhost:8108/stemming/dictionaries/import?id=set1"
```
Here `id` is dictionary name we want to store.

jsonl file should contain plurals in below format
```json
{"word": "meetings", "root":"meeting"}
{"word": "people", "root":"person"}
{"word": "attentions", "root":"attention"}
{"word": "leathers", "root":"leather"}
{"word": "qualities", "root":"quality"}
```
## get specific dictionary
To get the stored dictionary, we need to request via GET request to end-point `/stemming/dictionaries/:id` like below,
```curl
curl "http://localhost:8108/stemming/dictionaries/set1" -X GET -H "Content-Type: application/json" -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```
Here `set1` is the id of dictionary given while storing the dictionary. We will get the response like below.

```json
{"id":"set1","words":[{"root":"attention","word":"attentions"},{"root":"quality","word":"qualities"},{"root":"leather","word":"leathers"},{"root":"person","word":"people"},{"root":"meeting","word":"meetings"}]}
```
## get all stored dictionaries
To fetch all dictionary sets stored on typesense server, we need to send a GET request to end-point `/stemming/dictionaries` like below,
```curl
curl "http://localhost:8108/stemming/dictionaries" -X GET -H "Content-Type: application/json" -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```

Which will respond in below format,
```json
{"dictionaries":["set1"]}
```

## using the dictionary with collection search

We need to specify dictionary name while creating collection in order to use with searches in collection.
Here's how it can be created,
```curl
curl "http://localhost:8108/collections" \
       -X POST \
       -H "Content-Type: application/json" \
       -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" \
       -d '{
         "name": "companies",
         "fields": [
           {"name": "country", "type": "string", "stem_dictionary": "set1" }
       }'
```

Here `stem_dictionary` param specifies which dictionary to use for normalizing words while searching.

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Review by kishorenc — APPROVED** [review]

**Comment by b0g3r** [comment]
@krunal1313 @kishorenc thanks, it is really valuable feature for our use case. I see that POST endpoint works as "upsert", but in case I need to not only add new word to the list, but remove as well, what is the process?

**Comment by kishorenc** [comment]
Is there a reason you can't call `DELETE` and re-import? Or create a new v2 version of the dictionary via `/stemming/dictionary/import?id=set_v2` and then update the application to use that?

**Comment by PavelKoroteev** [comment]
> Is there a reason you can't call `DELETE` and re-import? Or create a new v2 version of the dictionary via `/stemming/dictionary/import?id=set_v2` and then update the application to use that?

Hello,@kishorenc.

I couldn't fine the DELETE method by testing, I checked the [openapi spec](https://github.com/typesense/typesense-api-spec/blob/master/openapi.yml) and I couldn't find the DELETE method for stemming dictionary as well. Is it missing or I'm missing something? Thank you in advance.

**Comment by kishorenc** [comment]
Ugh, looks like we implemented this but forgot to hook it up in the routes. I will get you a fixed build once this is addressed soon.

**Pull request merged**
