### PR TITLE
Option to return document ID and body in import response.

### PR DESCRIPTION
**Pull request by RedSnail**
## Change Summary
I've applied behaviour that I mentioned in #613 as optional, now you can get ID's of bulk-inserted documents if you specify "return_res" query parameter.

I've tested it and it's working.

## PR Checklist
- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by kishorenc** [comment]
@RedSnail 

Thank you for the PR! 

I like the idea of returning the `id` in the import response (as you've requested in https://github.com/typesense/typesense/issues/613), but I'm not sure about returning the full document -- the responses can get pretty large.  Can we stick to returning just the `id`?

**Comment by RedSnail** [comment]
> @RedSnail
> 
> Thank you for the PR!
> 
> I like the idea of returning the `id` in the import response (as you've requested in #613), but I'm not sure about returning the full document -- the responses can get pretty large. Can we stick to returning just the `id`?

I can specify both behaviours with different params. I'm developing an async client and I need a full document in response, 'cause I don't cache input entries by default to avoid memory pressure

**Comment by kishorenc** [comment]
👍 Adding both sounds good. Let's call the params as `return_id` and `return_document`.

**Comment by kishorenc** [comment]
Looks good now! My last comment is about adding a test, if it's not too much of a hassle, along the lines of this `ImportDocumentsEmplace ` test: https://github.com/typesense/typesense/blob/main/test/collection_test.cpp#L1252

Just need to assert for the presence of both `id` and `doc` fields in the response when the respective flags are enabled.

**Review by kishorenc — APPROVED** [review]

**Comment by kishorenc** [comment]
Merged, thank you for the contribution!

**Pull request merged**
