### PR TITLE
Support wildcard `facet_by`.

### PR DESCRIPTION
**Pull request by happy-san**
## Change Summary
#612 #825

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Review by kishorenc — APPROVED** [review]

**Comment by Clasyc** [comment]
Is there an docker image where I can access this feature?

**Comment by Clasyc** [comment]
nvm, it seems that it works on latest 0.25 rc tag

**Comment by pixelkoduje** [comment]
I see that instead of the `"*" error`, it shows the error 'Field `name` is not marked as a guy in the schema.'
I using `const data = useDynamicWidgets({
     guys: ['*']
   })` in docker version 0.25.0.rc9
It's not finished, do I need to do something else to make it work?
I'm using react-instantsearch-hooks-web

**Comment by kishorenc** [comment]
@pixelkoduje 

Can you post a larger snippet?

**Comment by pixelkoduje** [comment]
@kishorenc 
In this example you can see the dynamicWidget - in version 0.25.0.9rc you can see that instead of not working, it just shows an error (Add only typesense adapter to this only) `Field name is not marked as a guy in the schema.`:
https://github.com/algolia/instantsearch/tree/master/examples/react-hooks/next

I think we can easily make everything work in instantsearch react hooks. Just add some work and it will 1-1 work.

**Comment by KULTI1995** [comment]
@kishorenc you can see it more easily. By adding "face_by":"*" to the query
I noticed that version 0.25.0.9rc was added 8 days ago, and you have made a lot of changes since then. Are you able to upload the version after new updates to Docker Hub? I will test this and let you know.

**Pull request merged**
